/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JjiSwitchComp {
    }
}
export interface JjiSwitchCompCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLJjiSwitchCompElement;
}
declare global {
    interface HTMLJjiSwitchCompElement extends Components.JjiSwitchComp, HTMLStencilElement {
    }
    var HTMLJjiSwitchCompElement: {
        prototype: HTMLJjiSwitchCompElement;
        new (): HTMLJjiSwitchCompElement;
    };
    interface HTMLElementTagNameMap {
        "jji-switch-comp": HTMLJjiSwitchCompElement;
    }
}
declare namespace LocalJSX {
    interface JjiSwitchComp {
        "onCheckBoxCall"?: (event: JjiSwitchCompCustomEvent<boolean>) => void;
    }
    interface IntrinsicElements {
        "jji-switch-comp": JjiSwitchComp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "jji-switch-comp": LocalJSX.JjiSwitchComp & JSXBase.HTMLAttributes<HTMLJjiSwitchCompElement>;
        }
    }
}
